CREATE TABLE IF NOT EXISTS `role`
(
    `ROLE_ID`      INT          NOT NULL AUTO_INCREMENT,
    `ROLE_NAME`    VARCHAR(100) NOT NULL COMMENT '角色姓名',
    `CREATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    `UPDATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    PRIMARY KEY (`ROLE_ID`)
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;

